### PR TITLE
feat(PermissionOverwrite): allow params to be netural

### PR DESCRIPTION
**Pull request by spifory**
This fixes the mistake I made in #19

As permission overwrites can be set to Deny, **Neutral**, or Approve, that means that the correct typehint would be `Optional[bool]` to allow the user to use a None value.

### CODE REVIEW

**Comment by ooliver1** [comment]
:trollface:

**Review by ooliver1 — APPROVED** [review]
:neckbeard:

**Review by EmmmaTech — COMMENTED** [review]
Have you tested this?

**Comment by EmmmaTech** [comment]
Because of 8139572, I do not think that this PR is necessary. If you want to "set" a flag to a neutral value, just don't set it in the kwargs.

**Comment by spifory** [comment]
Well what if one were to change the permission's overwrites from `deny/allow` to `neutral`?

**Review by EmmmaTech — APPROVED** [review]

**Pull request merged**
